USE Librería;
GO

INSERT INTO Autor VALUES
(N'DANTE', N'ALIGHIERI', 1265, N'ITALIA'),
(N'JK', N'ROWLING', 1970, N'INGLATERRA')

INSERT INTO Autor(AñoDeNacimiento, AutorApellido, AutorNombre, Nación)
VALUES
(1960, N'COEHLO', N'PAULO', N'BRASIL'),
(1957, N'CERVANTES', N'MIGUEL', N'ESPAÑA')
;

